# DATABASE (LOCAL)
spring.datasource.url=jdbc:mysql://localhost:3306/climbup_db
spring.datasource.username=root
spring.datasource.password=Chithra@2619
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#nlty imai zxaf falj

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=climbupproductivity@gmail.com
spring.mail.password=nlty imai zxaf falj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
